# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from product_page import prodPage
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import json

allTeas = []
driver = webdriver.Edge()
url = "https://carturesti.ro/raft/ceai-758?brand=Casa%20de%20ceai&per-page=90"
urlPage2 = "https://carturesti.ro/raft/ceai-758?brand=Casa%20de%20ceai&page=2&per-page=90"
driver.get(url)
prod = WebDriverWait(driver, 10).until(EC.element_to_be_clickable(
    (By.XPATH, "//a[normalize-space()='Permite toate']")))
prod.click()
time.sleep(1)

prodInPage = 91

for _ in range(1, 3):
    for i in range(1, prodInPage):
        element = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable(
                (By.XPATH, f"//div[@class='cartu-grid-list']/div[{i}]/prod-grid-box[1]/div[1]/a[1]"))
        )
        element.click()
        prodPage(driver, allTeas)
        driver.get(url)
        time.sleep(1)

    prodInPage = 51
    url = urlPage2
    driver.get(url)
    time.sleep(1.5)


with open("data.json", "w", encoding='utf-8') as final:
    json.dump(allTeas, final, ensure_ascii=False)

driver.quit()
